### ISSUE TITLE
Migrate `datadog` package from glamplify to ca-go

### ISSUE THREAD

**Issue by AndrewMcCraeCA** [cultureamp/ca-go#272]
We want to port the `datadog` package from glamplify over to ca-go .
The glamplify repo has been archived and is not longer actively worked on.
We aim to make ca-go the source of truth for our shared packages.
Many repos still use the glamplify `datadog` package so we need to port it over to ensure it is maintained.
Move from here:
https://github.com/cultureamp/glamplify/tree/master/datadog
to here:
https://github.com/cultureamp/ca-go

**Comment by morgan121** [comment]
The datadog package relies on the glamify log package, which is quite different to the ca-go log package. There is a draft PR  (by Mike Ridgeway) currently to update the ca-go log package, which will change all the signatures, so until that is merged its best to leave this.
